<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<ProjectType>ProgramLibrary</ProjectType>
	</PropertyGroup>
	<PropertyGroup>
		<TargetFramework>net472</TargetFramework>
		<RootNamespace>PepperDash.Essentials.Plugin</RootNamespace>
		<Deterministic>false</Deterministic>
		<AssemblyTitle>PepperDash.Essentials.Plugin.Symetrix.DSP</AssemblyTitle>
		<Description>Symetrix Composer DSP Essentials Plugin</Description>
		<GenerateAssemblyInfo>true</GenerateAssemblyInfo>
		<OutputPath>bin\$(Configuration)\</OutputPath>
		<PackageId>PepperDash.Essentials.Plugin.Symetrix.DSP</PackageId>
		<PackageProjectUrl>https://github.com/PepperDash/epi-symetrix-dsp</PackageProjectUrl>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<DefineConstants>$(DefineConstants);SERIES4</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<DefineConstants>$(DefineConstants);SERIES4</DefineConstants>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="PepperDashEssentials" Version="2.12.1">
			<ExcludeAssets>runtime</ExcludeAssets>
		</PackageReference>
	</ItemGroup>
</Project>
